language: ruby
rvm:
- 2.3.1

install:
  - gem install bundler
  - bundle install

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production

sudo: false
