# Site settings
title: Simple is Better Than Complex
email: vitor@freitas.com
description: "This is a blog about Python, Django and Web Development. New posts every week."
baseurl: ""
url: "http://simpleisbetterthancomplex.com"
locale: en_US
twitter: "vitorfs"

# Build settings
markdown: kramdown

fb_admins: http://facebook.com/vitorfs
fb_appid: 1645747765697865

tag_page_layout: tag_page
tag_page_dir: tag

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"