# Site settings
title: Simple is Better Than Complex
email: vitor@freitas.com
description: "This is a blog about Python, Django and Web Development. New posts every week."
baseurl: ""
url: "https://simpleisbetterthancomplex.com"
locale: en_US
timezone: "Europe/Helsinki"
twitter: "vitorfs"

# Build settings
markdown: kramdown

fb_admins: https://facebook.com/vitorfs
fb_appid: 1645747765697865

gems:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5
paginate_path: "page:num"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vitor Freitas"